export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOG_OUT = "LOG_OUT"


export const SUCCESS =  'ALERT_SUCCESS'
export const ERROR = 'ALERT_ERROR'
export const CLEAR = 'ALERT_CLEAR'

export const REGISTER_REQUEST = "REGISTER_REQUEST"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"

export const GETALL_REQUEST= 'USERS_GETALL_REQUEST'
export const GETALL_SUCCESS= 'USERS_GETALL_SUCCESS'
export const GETALL_FAIL= 'USERS_GETALL_FAIL'

export const DELETE_REQUEST= 'USERS_DELETE_REQUEST'
export const DELETE_SUCCESS= 'USERS_DELETE_SUCCESS'
export const DELETE_FAIL= 'USERS_DELETE_FAIL'  